### ISSUE TITLE
용어집 (glossary) 구성 의견주세요

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#105]
주로 사용되는 용어, 번역하기 힘들거나 애매한 용어에 대해 의견 수렴을 거쳐 [용어집](https://github.com/golangkorea/golang-spec/blob/master/GLOSSARY.md)에 반영할 예정입니다. 용어에 알맞은 번역과 설명을 코멘트로 남겨주시고, 목록에 추가하고 싶은 용어 역시 코멘트 남겨주시기 바랍니다.

아래는 용어집에 추가될 후보군들입니다.

## 검토대기
- [ ] letter
- [ ] low-level programming
- [ ] newline
- [ ] receiver
- [ ] selector
- [ ] tag
- [ ] empty interface
- [ ] empty map
- [ ] zero-sized

## 1차 검토 완료
- [x] alignment = 얼라인먼트
- [x] base type = 기본 타입
- [x] blank identifier = blank 식별자
- [x] block = 블록
- [x] character = 캐릭터
- [x] declaration = 선언
- [x] identifier = 식별자
- [x] literal = 리터럴
- [x] signature = 시그니처
- [x] specification = 사양
- [x] token = 토큰
- [x] type = 타입
- [x] type alias = 타입 앨리어스
- [x] static type = 정적 타입
- [x] dynamic type = 동적 타입
- [x] underlying type = 내재 타입
- [x] composite type = 합성 타입
- [x] predeclared = 미리 선언된
- [x] assignment = 할당
- [x] index expressions = 인덱스 표현
- [x] key type = 키 타입
- [x] untyped = 미지정 타입
- [x] run-time panic = 런타임 패닉
- [x] equality operators = 동등 연산자
- [x] operand = 피연산자
- [x] label = 라벨
- [x] scope = 범위
- [x] statement = 구문 또는 문
- [x] function body = 함수 본문
- [x] illegal = 허용안됨. 문장에서 사용될 경우 `Go 문법에서는 ... 허용하지 않는다.`로 번역

**Comment by dakeshi** [comment]
아래 용어는 영문 그대로 번역하는게 좋을 것 같습니다.

```
type = 타입
type alias = 타입 앨리어스
character = 캐릭터
literal = 리터럴
```

- 타입은 상당히 익숙해진 용어라 별 무리없이 이해할 것 같습니다.
- type alias는 `타입 앨리어스` 또는 `타입 별칭` 이 가장 어울릴 것 같은데 `타입 별칭`이 `타입에 대한 별칭`을 연상시키지는 못하는 거 같아서 `타입 앨리어스` 가 더 끌리네요.
- 캐릭터는 문자라고 표현하기에는 letter, text 번역과도 연결되는 문제라 캐릭터로 번역하는게 가장 무난할 듯
- 리터럴은 다른 번역이 딱히 떠오르지 않네요.

**Comment by kesuskim** [comment]
@dakeshi 님의 의견에 동의합니다

그에 따라

- alignment는 뭐... 얼라인먼트는 이상하니 사전상 그대로인 정렬
- base type는 자연스레 기본 타입
- block 은 블록 이라고 그대로 읽는게 부드러운 것 같구요
- declaration은 의미 그대로 선언
- identifier도 의미 그대로 식별자


- newline  ...는... 참 애매하군요. 뭐라고해야되지. 문맥에 따라 다를것같은데요.
- operand 는 피연산자? 오퍼랜드? 개인적으로는 오퍼랜드의 의미가 더 잘 와닿긴합니다.

**Comment by jhonghee** [comment]
정렬이라는 말이 너무 보편적이고 여러 의미로 쓰인 단어라 alignment의 번역으로 적당한지 모르겠네요. alignment이 꽤 low-level 개념이라서 그냥 얼라인먼트(alignment)라고 번역하는게 좋을 것 같네요.

**Comment by HurSungYun** [comment]
[Method Declarations](https://golang.org/ref/spec#Method_declarations) 부분에서

```
A method is a function with a receiver.
```

라는 내용이 나옵니다.

일단 `수신자(receiver)`로 번역하였는데, receiver 자체가 Golang 에서 정의한 용어이니 좀 생각할 필요가 있어 보입니다.

**Comment by dakeshi** [comment]
token 도 추가해야겠네요. @ezaurum 님이 `언어요소` 로 번역해주셨는데 `토큰` 이 좀 더 일반적인 사용되는 용어라서 논의가 필요할 듯요.

**Comment by dakeshi** [comment]
signature 는 `시그니처`로 추가했습니다. 함수 시그니처는 그동안 많이 사용된 단어라 익숙할 것으로 판단되네요.

**Comment by dakeshi** [comment]
token은 `토큰`으로 추가했습니다.

**Comment by jhonghee** [comment]
blank identifier 는 identifier가 식별자로 번역되므로 blank 식별자라고 번역하는 것 좋겠습니다.

**Comment by jhonghee** [comment]
empty interface에 대한 번역을 할지 안할지 정하지 못했습니다.

**Comment by dakeshi** [comment]
specification 은 `사양` 이 적당할 듯 합니다.

**Comment by jhonghee** [comment]
static type = 정적 타입
dynamic type = 동적 타입

**Comment by dakeshi** [comment]
underlying type = 내재 타입
composite type = 합성 타입

**Comment by dakeshi** [comment]
predeclared = 미리 선언된

**Comment by voidsatisfaction** [comment]
promoted와 selector는 어떻게 해석해야할까요?

struct타입에 이런 문장이 있는데요.

A field or [method](/Declarations%20and%20scope/method_declarations.html) f of an embedded field in a struct x is called promoted if x.f is a legal [selector](/Expressions/selectors.html) that denotes that field or method f.

**Comment by jhonghee** [comment]
assignment = 할당
index expressions = 인덱스 표현
key type = 키 타입

**Comment by jhonghee** [comment]
untyped = 미지정 타입
run-time panic = 런타임 panic
equality operators = 대등 연산자

**Comment by dakeshi** [comment]
assignment = 할당
index expressions = 인덱스 표현
key type = 키 타입
untyped = 미지정 타입
run-time panic = 런타임 패닉
equality operators = 동등 연산자

으로 1차 검토대상에 추가합니다.

**Comment by ezaurum** [comment]
@kesuskim 
> operand 는 피연산자? 오퍼랜드? 개인적으로는 오퍼랜드의 의미가 더 잘 와닿긴합니다.

피연산자가 좋을 듯 합니다.  Operator를 연산자로 번역하니 짝을 맞추는 쪽이 이해에 도움이 될 거라 생각합니다.

**Comment by mitrilmad** [comment]
labels = 라벨
scope = 범위

어떤가요?

**Comment by ezaurum** [comment]
> labels = 라벨
scope = 범위

@mitrilmad 저는 좋아보입니다.

**Comment by dakeshi** [comment]
operand = 피연산자
label = 라벨
scope = 범위
statement = 구문, 문
function body = 함수 본문
illegal = 허용안됨. 문장에서 사용될 경우 `Go 문법에서는 ... 허용하지 않는다.`로 번역

으로 1차 검토대상에 추가합니다.

**Comment by ezaurum** [comment]
statement = 문 으로 일단 번역하고 있습니다.
괜찮은 게 또 안 떠오르네요.

**Comment by jhonghee** [comment]
goroutine = 고루틴
first-in-first-out queues = 선입-선출 큐

**Comment by dakeshi** [comment]
zero-sized 는 마땅한 번역이 없네요. 검토대기에 추가하겠습니다.

**Comment by dakeshi** [comment]
sequence 는 보통 `연속`으로 번역했는데 `집합`, `그룹`의 의미로 번역하는게 문맥상 어울리는 경우가 맞네요. 일단은 `연속`으로 남겨두고 적당한 번역을 고민해보시죠.

**Comment by ezaurum** [comment]
`variadic` 같은 경우, `가변인자 함수` 가 널리 쓰는 표현이라 그 쪽이 이해가 쉬울 듯 합니다.

**Comment by jhonghee** [comment]
Arithmetic Operators 섹션에 truncated division라는 말이 나오는데 한글로 번역이 어렵네요. 뜻은 x / y에서 소수점이하을 절단할때 0값을 겨냥해서 하는 것입니다. 이것은 floored division이 무한히 작은 음수를 향해 소수점이하를 절단하는 방식과 대비됩니다. 제가 제안하는 번역은

truncated division => 절단식 나누기
floored division => 내리기식 나누기

**Comment by jhonghee** [comment]
dividend => 피제수
divisor => 제수

**Comment by jhonghee** [comment]
right shift => 우향 시프트
left shift => 좌향 시프트

**Comment by jhonghee** [comment]
modulo => 모듈로

**Comment by jhonghee** [comment]
wrap around는 계산 값이 허용하는 최대치를 넘는 경우 모자라는 값만큼 다시 시작 값에서 결괏값을 취하는 연산을 설명하는 것 같네요. modulo를 이용한 계산과 같은 의미인 것 같은데, 번역을 어떻게 해야 할지 애매합니다. 일반적으로 wrap around가 두루다로 번역되는 것 같아서 그냥 "값 두루기" 정도로 번역하면 어떨까요?

Loosely speaking, these unsigned integer operations discard high bits upon overflow, and programs may rely on "wrap around".

**Comment by dakeshi** [comment]
용어집 구성은 transifex 용어집으로 대체하며 개별 단어에 대한 번역 용어 논의는 별도의 issue 로 오픈해주시거나 gitter 채팅창에 의견을 남겨주시면 transifex 용어집에 반영하도록 하겠습니다.
