### ISSUE TITLE
slice타입 typo

### ISSUE THREAD

**Issue by voidsatisfaction** [golangkorea/golang-spec#126]
### 체크리스트
- [x] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 

### Issue 설명(선택사항)
> 슬라이즈는 내재하는 array의 연속된 한 조각에 대해 서술한 것이며 그 array로 부터 숫자가 매겨진 연속된 요소들에 접근을 하게 해 준다. 슬라이스 타입은 그 요소 타입으로 구성된 array들의 모든 슬라이스를 포함하는 집합을 의미한다. 초기화 되지 않은 슬라이스의 값은 nil이다. 

가장 앞에 슬라이즈 => 슬라이스

### 수정 요청
슬라이즈 => 슬라이스

**Comment by dakeshi** [comment]
리뷰 감사합니다. 오늘 중으로 슬라이스 챕터 리뷰진행하면서 반영하도록 하겠습니다.

**Comment by dakeshi** [comment]
https://www.transifex.com/golang-korea/go-specification/translate/#ko/types_slice_typesmd

리뷰 시작합니다. #285

**Comment by dakeshi** [comment]
리뷰 완료되었습니다.
