### ISSUE TITLE
Built-in functions/Handling panics 번역

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#181]
지원자: Joseph Kim

**Comment by potatogim** [comment]
https://www.transifex.com/golang-korea/go-specification/translate/#ko/built-in_functions_handling_panicsmd/130648921

리뷰 부탁드립니다~

**Comment by dakeshi** [comment]
리뷰중입니다.

**Comment by dakeshi** [comment]
리뷰 완료
