### ISSUE TITLE
Declarations and scope/Exported identifiers 번역

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#189]
지원자: 한민석

**Comment by dakeshi** [comment]
https://www.transifex.com/golang-korea/go-specification/translate/#ko/declarations_and_scope_exported_identifiersmd/

**Comment by mitrilmad** [comment]
번역 완료 했습니다.

**Comment by dakeshi** [comment]
리뷰 시작합니다.

**Comment by dakeshi** [comment]
리뷰 완료
