### ISSUE TITLE
Introduction/README 번역

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#224]
지원자: 윤정부

**Comment by jhonghee** [comment]
https://www.transifex.com/golang-korea/go-specification/translate/#ko/introduction_readmemd/130508986

번역 시작

**Comment by jhonghee** [comment]
번역 완료

**Comment by dakeshi** [comment]
리뷰 시작

**Comment by dakeshi** [comment]
리뷰 완료
