### ISSUE TITLE
Statements/Fallthrough statements 번역

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#260]

**Comment by ezaurum** [comment]
제가 보드를 못 보고 작업을 먼저 해 버렸습니다.
짧은 게 있길래 그만...
한 번 확인 부탁드립니다.

**Comment by dakeshi** [comment]
https://www.transifex.com/golang-korea/go-specification/translate/#ko/statements_fallthrough_statementsmd/130649615

**Comment by dakeshi** [comment]
그러셨군요. 일단 번역 완료로 옮기도록 하겠습니다.

**Comment by jhonghee** [comment]
제 리뷰는 완료되었습니다.

**Comment by ezaurum** [comment]
번역 제안대로 수정했습니다.

**Comment by dakeshi** [comment]
제안 수용되었으므로 완료 처리하겠습니다.
