### ISSUE TITLE
Statements/Labeled statements 번역

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#266]

**Comment by jhonghee** [comment]
https://www.transifex.com/golang-korea/go-specification/translate/#ko/statements_labeled_statementsmd/130649671

**Comment by jhonghee** [comment]
https://www.transifex.com/golang-korea/go-specification/translate/#ko/statements_labeled_statementsmd/130649670

**Comment by jhonghee** [comment]
완료
