### ISSUE TITLE
부동 소수점 리터럴에서 예시 부분이 빠져있음

### ISSUE THREAD

**Issue by voidsatisfaction** [golangkorea/golang-spec#295]
### 체크리스트
- [x] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 

### Issue 설명(선택사항)
https://golang.org/ref/spec#Floating-point_literals

https://gosudaweb.gitbooks.io/go-language-specification-in-korean/content/ko/Lexical%20elements/floating-point_literals.html

부동 소수점 리터럴에서 예시 부분이 빠져있네요

**Comment by jhonghee** [comment]
Multi-Language 로 변환하면서 실수로 없어진 것 같네요. 복원하겠습니다.

https://github.com/golangkorea/golang-spec/commit/954fade5a3f7b1f0f38f37d1d741a3e0610f604e#diff-d2f4b50d42211079dc5b5f161d8622e8

**Comment by jhonghee** [comment]
master 브랜치에 복원했습니다.
