### ISSUE TITLE
번역 가이드 확장. Go EBNF 및 타입 관련

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#30]
번역시 영어 원문을 유지해야 하는 용어들에 대한 목록을 작성하기 위해 몇 가지 규칙을 제안하고자 합니다.

1. EBNF에 따라 작성된 Go 문법은 번역하지 않습니다.
예를 들면,  [Types 섹션](https://golang.org/ref/spec#Types)에 나오는 문법 표현은 아래와 같습니다.

```
Type      = TypeName | TypeLit | "(" Type ")" .
TypeName  = identifier | QualifiedIdent .
TypeLit   = ArrayType | StructType | PointerType | FunctionType | InterfaceType |
	    SliceType | MapType | ChannelType .
```

문법 표현은 한글로 번역하지 않고 원문 그대로 유지하시면 됩니다.

2. EBNF에 따라 작성된 Go 문법에서 가장 왼쪽에 해당하는 용어가 문장에서 사용된 경우, 영어 원문을 유지하는 것을 기본으로 합니다. EBNF에 따라 작성된 Go 문법에서 가장 왼쪽에 해당하는 용어는 다음과 같습니다.
```
AliasDecl
ArrayLength
ArrayType
BaseType
big_u_value
Block
byte_value
ChannelType
ConstDecl
ConstSpec
decimal_digit
decimal_lit
Declaration
ElementType
EmbeddedField
exponent
ExpressionList
FieldDecl
float_lit
Function
FunctionBody
FunctionDecl
FunctionName
FunctionType
hex_byte_value
hex_digit
hex_lit
identifier
IdentifierList
imaginary_lit
int_lit
InterfaceType
InterfaceTypeName
interpreted_string_lit
KeyType
letter
little_u_value
MapType
MethodDecl
MethodName
MethodSpec
newline
octal_byte_value
octal_digit
octal_lit
Operand
ParameterDecl
ParameterList
Parameters
PointerType
raw_string_lit
Receiver
Result
rune_lit
ShortVarDecl
Signature
SliceType
StatementList
string_lit
StructType
Tag
TopLevelDecl
Type
TypeDecl
TypeDef
TypeLit
TypeName
TypeSpec
unicode_char
unicode_digit
unicode_letter
unicode_value
VarDecl
VarSpec
```

예를 들면, [identifiers 섹션](https://golang.org/ref/spec#Identifiers)에 나오는 문법 표현은 아래와 같습니다.

```
identifier = letter { letter | unicode_digit } .
```

위의 문법에서 가장 왼쪽에 해당하는 `identifier`가 문장에서 언급된 경우, 한글로 번역하지 않고 영어 원문을 유지합니다. 따라서, [identifiers 섹션](https://golang.org/ref/spec#Identifiers)에 언급된 아래 문장의 경우,

> Some identifiers are predeclared.

`어떤 identifier는 미리 선언되어있다.` 라고 번역하시면 됩니다.

3. EBNF에 따라 작성된 Go 문법에서 가장 왼쪽에 해당하는 용어가 문장에서 사용된 경우라도, 아래에 해당하는 용어는 다음과 같이 번역합니다. 

Declaration : 선언
Function : 함수
Block : 블록
Signature : 시그니처
Tag : 태그
Type : 타입

추가로 각종 타입들도 영어 원문을 유지했으면 합니다. 즉, `문자열 타입` 대신 `string 타입`이라고 번역해야 하는거지요. 코드에서 `string` 타입이 사용되기 때문에 이렇게 번역하는게 좋다고 생각합니다.

작성하고 나니 규칙이 복잡해 보이기도 하네요. 좀 더 문서를 수정할 필요가 있겠네요. 의견 남겨주세요.

**Comment by jhonghee** [comment]
제가 원본을 markdown으로 옮길때 EBNF로 링크 걸린 단어들을 다 보존해 놓았습니다. 그래서 EBNF 의 해드로 사용된 토큰인지 알 수 있는 또 하나의 방법은 ENBF로 hyperlink가 되어 있는지 보면 쉽게 판단할 수 있습니다. 그럴 경우 2번에서 말씀하신 것 처럼 굿이 번역하지 않아도 되지만 꼭 번역을 해야 한다면 옆에 괄호를 사용해 원문 링크를 보존하면 좋을 것 같습니다.

```
[식별자](/Lexical elements/identifiers.html) -> 식별자 [(identifier)](/Lexical elements/identifiers.html)
```

**Comment by dakeshi** [comment]
링크가 있는 경우 번역하지 않는 것도 좋은 방법이네요. 다만, 번역 또는 번역하지 않아도 된다로 가면 규칙이 더욱 복잡해질 가능성이 있고 전체 글 통일성을 위해 둘 중 하나만 유지하는게 좋을 거 같습니다. 전 번역하지 않는다에 한표 🙌  번역이 필요하면 번역 완료되고 이 용어들만 별도로 번역 진행하는 방법도 있겠네요.

타입을 번역하지 않고 원문 그대로 유지하는 것에 대해서도 의견 주시면 감사하겠습니다. 

string 타입, 문자열 타입
slice 타입, 슬라이스 타입

타입은 spec에 상당히 많이 사용되는 단어들이라 초기에 규칙을 정하는게 좋을 것 같습니다.

**Comment by ezaurum** [comment]
문자열 대신에 string을 쓰는 것은 합당해 보입니다. 코드에 사용되는 기호와 동일한 것이 좋다고 생각합니다.

**Comment by ezaurum** [comment]
EBNF는 번역을 하는 것이 좋다고 생각합니다.
코드의 경우는 코드에 직접 영문자를 적어넣어야 하니 직결되는 것이 의미가 있지만, EBNF는 의미를 이해하는 것이 먼저라 한글로 적는 것이 좋다고 봅니다.

**Comment by jhonghee** [comment]
@ezaurum  저는 EBNF 번역에 회의적인 입장입니다. 처음 몇줄에 있는 comment는 당연히 번역을 해야 겠지요. 예를 들어
newline        = /* the Unicode code point U+000A */ .
newline        = /* 유니코드 위치 U+000A */ .

하지만 나머지는 모두 문법을 묘사하는 코드라고 생각해야 할 것 같아요. 코드를 굳이 한글로 변환할 이유는 없다고 봅니다.

**Comment by dakeshi** [comment]
@jhonghee @ezaurum 의견 주셔서 감사합니다. 용어에 대한 한글 번역은 모든 글이 완료된 이후에도 적용가능하니 우선 다음과 같이 진행하도록 하겠습니다.

- EBNF로 표현된 구문: 주석을 제외하고 영문을 유지
- EBNF 관련 예약어: 영문 유지
- 타입: 영문 유지 (ex) string 타입, array 타입
- EBNF 관련 예약어 예외 적용(glossary에 추가 예정)
Block : 블록
Declaration : 선언
Function : 함수
identifier: 식별자
Signature : 시그니처
Tag : 태그
Type : 타입

**Comment by dakeshi** [comment]
README에 EBNF 관련 규칙 반영했구요 번역 필요한 용어는 용어집에 추가하는 것으로 하겠습니다.
