### ISSUE TITLE
untyped/typed constant, base type(of pointer) 번역 용어 통일

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#313]
### 체크리스트
- [x] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 

### Issue 설명(선택사항)
untyped/typed constant, base type(of pointer) 번역 용어가 챕터 별로 약간씩 차이가 있습니다.

* 번역 추천
untyped constant: 미지정 타입 상수
typed constant: 타입 정보가 있는 상수 또는 타입이 지정된 상수
base type: 기본 타입(용어집 등록됨) 또는 기초 타입
defined type: 타입 정의를 이용해 만든 타입(용어집 등록됨) 또는 type 예약어로 정의한 타입

### 부가 설명
우선, 코멘트에 용어 추천 번역 의견 주시길 바랍니다.

1. 의견이 모아지는 대로 용어집에 등록하고
2. 번역 대상 챕터 transifex 링크 추가해서, 통일된 용어로 번역 수정한 다음
3. 기존 번역 수정 완료되면 이슈는 닫도록 하겠습니다.

**Comment by ezaurum** [comment]
type constant 는 typed constant 지요?
untyped constant:  타입 미지정 상수
typed constant: 타입 지정 상수
base type: 기본 타입
untyped <=> typed 짝을 맞추는 게 좋을 듯 합니다.

**Comment by dakeshi** [comment]
타입과 관련된 번역은 string 타입, 불리언 타입 등과 같은 형태로 번역하고 있습니다. 이 기준을 적용하면 untyped constant는 다음과 같이 번역하는 것이 좋을 것 같습니다.

untyped constant: 미지정 타입 상수

typed constant 의 경우 `지정 타입 상수` 라고 번역하면 부자연스럽게 느껴지기 때문에 아래와 같이 번역하는게 좋을 것 같습니다.

typed constant: 타입 지정 상수

base type: 기본 타입. 

defined type 이 가장 고민되는 부분이네요.

**Comment by dakeshi** [comment]
토의 결과:

untyped constant: 미지정 타입 상수
typed constant: 타입 지정 상수
base type: 기본 타입
defined type: 타입 정의를 이용해 만든 타입
