### ISSUE TITLE
원본 업데이트

### ISSUE THREAD

**Issue by jhonghee** [golangkorea/golang-spec#7]
golangkorea/golang-spec은 2016년 9월 8일자 go spec 원문을 바탕으로 레포가 만들어진 후 아직 업데이트되지 않았습니다.

10월 4일이후 commit된 go spec 원문 내용을 업데이트하여 주십시요.

https://github.com/golang/go/commits/master?after=a5b759aab8b9e866c0bf2dd91ffde68b6bc6766b+34&path%5B%5D=doc&path%5B%5D=go_spec.html

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/5c7a005266f84ecea26859619630a862eccc0d48#diff-94792ed6b8d17736ee79af0ca532d6fe, Oct5, 2016, 업데이트했습니다. 

fix in: #9

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/a016ecfdcbc266f45f33350238777fba9a391b8d#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in : https://github.com/golangkorea/golang-spec/pull/11

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/5567b878915f7c2f1e7ee3898125c2cd2b7fe287#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in: https://github.com/golangkorea/golang-spec/pull/13

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/8fbfdad28145bfaad2fa2082336128944d5a3543#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in : https://github.com/golangkorea/golang-spec/pull/14

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/023bb034e93363492ef444fefcb1d38cdc61ede1#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in: https://github.com/golangkorea/golang-spec/pull/15

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/aff37662d1f70f2bf9e47b4f962e85521e7c18d1#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in : https://github.com/golangkorea/golang-spec/pull/16

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/7fd6b925e38f67c2d0cb3fca0f3dc8b6d…

fix in: #17

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/87f4e36ce7d7dffbf1f2a869f3014321f6cfff3c#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in: #18

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/120cf676caff29296de2dd16a2997463eb6e1579#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in: #19

**Comment by dakeshi** [comment]
https://github.com/golang/go/commit/0eb26fa8ba531b21d183fd3a4d3fb8abf57db7aa#diff-94792ed6b8d17736ee79af0ca532d6fe

fix in: #20

**Comment by dakeshi** [comment]
golang/go@b01f612

fix in: #22

**Comment by dakeshi** [comment]
오늘은 여기까지. 2016년 commit은 모두 적용했습니다. 

2017년도 커밋 f8b4123 부터 적용하시면 됩니다.

**Comment by dakeshi** [comment]
golang/go@f8b4123

fix in: #34

**Comment by HurSungYun** [comment]
[golang/go@56c9b51](https://github.com/golang/go/commit/56c9b51b937cca7d3db517add96bd9517bbffb80#diff-94792ed6b8d17736ee79af0ca532d6fe)

fix in: #45

**Comment by jhonghee** [comment]
https://github.com/golang/go/commit/c0bd4f33ccc9a9454d50245a1dba1fa46e62a1ad#diff-94792ed6b8d17736ee79af0ca532d6fe

**Comment by jhonghee** [comment]
https://github.com/golang/go/commit/e62aab1274c25364fe8c4609c17cb0d8e57b78d0#diff-94792ed6b8d17736ee79af0ca532d6fe

**Comment by jhonghee** [comment]
https://github.com/golang/go/commit/866f63e84eb7096e64b7a39b993c2ca3e943e425#diff-94792ed6b8d17736ee79af0ca532d6fe

**Comment by jhonghee** [comment]
https://github.com/golang/go/commit/26e726c3092264584053a4f81714dcc8c91d2153#diff-94792ed6b8d17736ee79af0ca532d6fe

**Comment by jhonghee** [comment]
https://github.com/golang/go/commit/369d1083a74b6a965a33510489ab381d937812ae#diff-94792ed6b8d17736ee79af0ca532d6fe

**Comment by jhonghee** [comment]
https://github.com/golang/go/commit/b0e5a0c93ccf5166dab30864df7e5632a5973447#diff-94792ed6b8d17736ee79af0ca532d6fe

**Comment by jhonghee** [comment]
https://github.com/golang/go/commit/94b6011c78484357ef632f3cce3b382a0bc4c2cf#diff-94792ed6b8d17736ee79af0ca532d6fe

**Comment by jhonghee** [comment]
나머지 원본 커밋들은 개별 issue로 만들어 올리겠습니다. 작업을 하시기 전에 작업중이라는 comment를 달아 주세요.

**Comment by jhonghee** [comment]
남은 원본 커밋은 모두 개별 issue로 등록되었습니다. 작업하시기 전에
1) assignee를 본인으로 해주시고
2) 작업중이라는 코멘트를 남겨주세요

이것으로 이 issue는 close하겠습니다.

**Comment by dakeshi** [comment]
go 버전 1.9 기준으로 작성된 스펙은 #58 번까지 적용하면 됩니다. 현재 영어 원본 업데이트와 관련해서는 #71 커밋까지 작성된 상태입니다. 이후 발생된 원본 업데이트도 커밋 링크 추가해서 issue 오픈하면 라벨을 spec sync로 붙여서 관리하도록 하겠습니다.
